stages:
    - build

build:clippy:
    stage: build
    tags:
        - docker
    image: "rust:1-bullseye"
    script:
        - apt update -qy
        - apt install -qy libclang-dev build-essential pkg-config clang nettle-dev gettext zsh
        - rustup component add clippy
        - RUST_BACKTRACE=full cargo clippy

build:binary:
    stage: build
    tags:
        - docker
    image: "rustlang/rust:nightly"
    script:
        - apt update -qy
        - apt install -qy libclang-dev build-essential pkg-config clang nettle-dev gettext zsh
        - ./make-translated-templates
        - RUST_BACKTRACE=full cargo build
        - RUST_BACKTRACE=full cargo test --all
