[package]
name = "garbage-pile"
version = "0.1.0"
authors = ["seu <seu@panopticon.re>"]

[dependencies]
rocket = "0"
rocket_codegen = "0"
openpgp =  { path = "../sequoia/openpgp" }
multipart = "0"
error-chain = "0"
log = "0"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.9"
time = "0.1"
tempfile = "3.0"
parking_lot = "0.6"
structopt = "0.2"
