[package]
name = "hagrid"
version = "0.1.0"
authors = ["Kai Michaelis <kai@sequoia-pgp.org>"]
build = "build.rs"

[dependencies]
rocket = "0"
rocket_codegen = "0"
sequoia-openpgp = "0.4.1"
multipart = "0"
error-chain = "0"
log = "0"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
tempfile = "3.0"
parking_lot = "0.6"
structopt = "0.2"
url = "1.6"
hex = "0.3"
lettre_email = "0.8"
handlebars = "1.1.0"
base64 = "0.10"

[dependencies.lettre]
version = "0.8"
default-features = false
# smtp-transport doesn't build (openssl problem)
features = ["file-transport", "sendmail-transport"]

[dependencies.rocket_contrib]
version = "0"
default-features = false
features = ["handlebars_templates"]

[build-dependencies]
vergen = "3"
